#! /bin/bash

tmppo="/tmp/all.po"
files=`find apps/ -name fr.po`
msgcat="msgcat"
for i in $files
do
	msgcat="$msgcat $i"
done
msgcat="$msgcat -o $tmppo"
$msgcat

msgfmt $tmppo -o locale/fr_FR/LC_MESSAGES/messages.mo

